name: Build and Test

on:
  push:
    paths-ignore:
      - '**.json'
      - '**.md'

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Run yamllint with common config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run yamllint
        run: yamllint -c .github/linters/.yaml-lint.yaml .github/

  security:
    name: Run Snyk to check for vulnerabilities
    # if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@master

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.8@master
        continue-on-error: true  # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --severity-threshold=high --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

  build:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", 3.11]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-build.txt

      - id: ToxSetting
        run: |
          if [[ "${{ matrix.python-version }}" == "3.8" ]]
          then
            echo "toxenv=py38" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.python-version }}" == "3.9" ]]
          then
            echo "toxenv=py39" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.python-version }}" == "3.10" ]]
          then
            echo "toxenv=py310" >> $GITHUB_OUTPUT
          elif [[ "${{ matrix.python-version }}" == "3.11" ]]
          then
            echo "toxenv=py311" >> $GITHUB_OUTPUT
          else
            exit 1
          fi

      - name: Test with tox
        run: |
          tox -r -e ${{ steps.ToxSetting.outputs.toxenv }}
